# Base Docker Compose Configuration
# This file contains shared services and internal networking setup
# Use with environment-specific override files:
#   Development: docker-compose -f docker-compose.yml -f docker-compose.dev.yml
#   Production:  docker-compose -f docker-compose.yml -f docker-compose.prod.yml

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hrms}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hrm_network

  # FastAPI Backend
  backend:
    build: ../backend
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:mysecretpassword@database:5432/hrms}
      CREATE_SEED_DATA: ${CREATE_SEED_DATA:-true}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - hrm_network

  # Next.js Frontend
  frontend:
    build: ../frontend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hrm_network

volumes:
  postgres_data:

networks:
  hrm_network:
    driver: bridge